name: Atualizar Totoloto automaticamente

# horario: verao

on:
  schedule:
    - cron: "10 7 * * 4"     # quintas, 08:10 em Portugal (07:10 UTC)
    - cron: "10 7 * * 0"     # domingos, 08:10 em Portugal (07:10 UTC)
    - cron: "11 23 * * 1"    # terças, 00:11 em Portugal (23:11 UTC de segunda)
  workflow_dispatch:  # permite executar manualmente no GitHub

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Instalar dependências Python
        run: |
          pip install requests beautifulsoup4

      - name: Rodar script de scraping
        run: python scripts/atualizar_totoloto.py

      - name: Commit e push das alterações
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add dados/
          git add logs/totoloto_log.txt
          # Só faz commit/push se houver mudanças
          if ! git diff --cached --quiet; then
            git commit -m "Atualização automática Totoloto"
            git push
          else
            echo "Nenhuma alteração, nada para commitar."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
