name: Atualizar Totoloto automaticamente

on:
  schedule:
    - cron: "0 9 * * 1,3,5"
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Instalar dependências Python
        run: |
          pip install requests beautifulsoup4

      - name: Rodar script de scraping
        run: python scripts/atualizar_totoloto.py

      - name: Commit e push das alterações
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Atualização automática Totoloto"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
