name: dependências

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          # Especifique a versão exata do Python que o pip está a usar
          # Com base no seu log, o pip está a usar 3.13.7
          python-version: "3.13" 

      - name: Instalar dependências e executar scripts
        run: |
          # Use o python configurado pela ação para garantir consistência
          python -m pip install --upgrade pip
          pip install -r requirements.txt  
          python treinar_decisor.py  
          python gerar_previsao.py
