name: Enviar email Totoloto

# horario: verao

on:
  schedule:
    - cron: "55 21 * * 3"   # quartas, 22:55 em Portugal (21:55 UTC)
    - cron: "55 21 * * 6"   # sábados, 22:55 em Portugal (21:55 UTC)
  workflow_dispatch:

jobs:
  enviar_email:
    runs-on: ubuntu-latest

    steps:
    - name: Fazer checkout do repositório
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Instalar dependências (se necessário)
      run: |
        python -m pip install --upgrade pip
        # Se tiveres dependências, instala aqui, por exemplo:
        # pip install -r requirements.txt
      # No caso do script simples, não precisas instalar nada.

    - name: Enviar email
      env:
        EMAIL_REMETENTE: ${{ secrets.EMAIL_REMETENTE }}
        SENHA_APP: ${{ secrets.SENHA_APP }}
        EMAIL_DESTINO: ${{ secrets.EMAIL_DESTINO }}
      run: |
        python scripts/enviar_email.py
