name: Enviar email Totoloto

on:
  schedule:
    - cron: "2 8 * * 4"     # quintas, 08:02 UTC
    - cron: "2 8 * * 0"     # domingos, 08:02 UTC
    - cron: "3 0 * * 2"     # terças, 00:03 UTC
  workflow_dispatch:

jobs:
  enviar_email:
    runs-on: ubuntu-latest

    steps:
    - name: Fazer checkout do repositório
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Instalar dependências (se necessário)
      run: |
        python -m pip install --upgrade pip
        # Se tiveres dependências, instala aqui, por exemplo:
        # pip install -r requirements.txt
      # No caso do script simples, não precisas instalar nada.

    - name: Enviar email
      env:
        EMAIL_REMETENTE: ${{ secrets.EMAIL_REMETENTE }}
        SENHA_APP: ${{ secrets.SENHA_APP }}
        EMAIL_DESTINO: ${{ secrets.EMAIL_DESTINO }}
      run: |
        python scripts/enviar_email.py
