name: Gerar Previsão Completa do Totoloto

on:
  schedule:
    - cron: '30 8 * * *'  # Exemplo: 8h00 UTC, ajuste conforme necessário
  workflow_dispatch:

jobs:
  gerar_previsao:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Python e Dependências
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Executar o avaliador e o gerador de previsão
        run: |
          echo "Executando o avaliador/incrementador..."
          python avaliador/avaliador.py
          echo "Gerando a nova previsão..."
          python gerar_previsao.py
        env:
          PYTHONPATH: ${{ github.workspace }}
          
      - name: Fazer commit dos arquivos gerados
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git

          # Adiciona os novos ficheiros e pastas da nova arquitetura
          git add previsoes/previsao_atual.json
          git add previsoes/*.json
          git add decisor/modelos_salvos
          git add decisor/metadados_modelo.json
          git add decisor/sorteio_processado.json
          
          # Verifica se há alterações antes de fazer o commit
          git diff --cached --quiet || git commit -m "Atualização automática de modelo e previsão"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
