name: Gerar Estatísticas

on:
  workflow_dispatch:  # permite executar manualmente no GitHub
  push:
    paths:
      - 'dados/**'
      - 'js/estatisticas.js'

jobs:
  gerar-json:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Correr script estatísticas.js
        run: node js/estatisticas.js

      - name: Commit e Push do JSON gerado
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add estatisticas/estatisticas_stacasa.json
          git commit -m "Atualizar estatísticas automaticamente" || echo "Sem alterações"
          git push
