name: Gerar Estatísticas

# horario: verao

on:
  schedule:
    - cron: "59 21 * * 3"   # quartas, 22:59 em Portugal (21:59 UTC)
    - cron: "59 21 * * 6"   # sábados, 22:59 em Portugal (21:59 UTC)
  workflow_dispatch:  # permite executar manualmente no GitHub
  push:
    paths:
      - 'dados/**'
      - 'js/**'
      - '**/*.py'

jobs:
  gerar-json:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      # Passo 1: Configura o ambiente Node.js e corre o script JavaScript
      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Correr script estatísticas.js
        run: node js/estatisticas.js

      # Passo 2: Configura o ambiente Python para correr os scripts de análise
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Instalar bibliotecas Python
        run: |
          python -m pip install --upgrade pip
          
      - name: Correr Avaliação Incremental (Python)
        run: python avaliador_incremental.py

      - name: Correr Análise de Combinações (Python)
        run: python analisador_combinacoes.py

      - name: Commit e Push dos Relatórios gerados
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          # Adiciona todos os ficheiros modificados na pasta 'estatisticas/'
          git add estatisticas/
          git diff --staged --quiet || (git commit -m "Atualizar relatórios automaticamente" && git push)
