name: Gerar Previsão Totoloto

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  gerar_previsao:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # necessário para o commit manual

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Executar gerar_previsao.py
        run: python gerar_previsao.py

      - name: Mostrar previsão gerada
        run: cat previsoes/previsao_atual.json

      - name: Avaliar heurísticas e atualizar pesos
        run: python avaliador/avaliador.py

      - name: Fazer commit dos JSONs gerados
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git

          git add previsoes/previsao_atual.json
          git add decisor/pesos_atuais.json
          git add decisor/historico_performance.json
          git diff --cached --quiet || git commit -m "Atualiza previsão/pesos automática"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
