name: Treinar e Salvar o Modelo

on:
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Instalar Dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Executar o Treino do Modelo
        run: |
          python treinar_decisor.py
      
      - name: Commitar e Enviar os Novos Ficheiros
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Adiciona os novos ficheiros gerados pelo script `treinar_decisor.py`
          git add decisor/modelo_previsor.joblib
          git add decisor/metadados_modelo.json
          
          # Tenta commitar. Se não houver alterações, o comando || echo evita que o workflow falhe.
          git commit -m "feat(decisor): Atualiza modelo de ML e metadados" || echo "Nenhuma alteração a commitar"
          
          # Garante que o push é feito para o repositório principal
          git push
