name: Treinar e Salvar o Modelo

on:
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Instalar Dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Executar o Treino do Modelo
        # Define o PYTHONPATH para a raiz do repositório
        # Isso garante que as importações 'from lib.dados...' funcionem
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          python treinar_decisor.py
      
      - name: Commitar e Enviar os Novos Ficheiros
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          git add decisor/modelo_previsor.joblib
          git add decisor/metadados_modelo.json
          
          # Verifica se há alterações antes de fazer o commit
          if git diff --staged --quiet; then
          echo "Nenhuma alteração nos arquivos do modelo. Nenhuma ação necessária."
          else
          git commit -m "feat(decisor): Atualiza modelo de ML e metadados"
          git push
          fi
